void loadimages () {

  //Imagens do menu principal

  narrativaM[0] = requestImage("menu/A000.png"); //background
  narrativaM[1] = requestImage("menu/A001.png"); //Samira 2 F
  narrativaM[2] = requestImage("menu/A002.png"); //Julia 3 C
  narrativaM[3] = requestImage("menu/A003.png"); //Bernardo 4 E
  narrativaM[4] = requestImage("menu/A004.png"); //Camila 5 D
  narrativaM[5] = requestImage("menu/A005.png"); //João 6 E
  //era  joao 2 B,  julia 3 C , camila 4 D, bernardo 5E,  samira 6F
  // agora é samira 2f, julia 3c, bernardo 4e, camila 5d, joao 6e
  

  //Imagens do menu tutorial

  narrativaT[0] = loadImage("tela descanso/TD001.png");
  narrativaT[1] = loadImage("tela descanso/TD002.png");
  narrativaT[2] = requestImage("tela descanso/TD003.png");
  narrativaT[3] = requestImage("tela descanso/TD004.png");
  
  headerNarrativa[0] = requestImage("narrativa/B_João/B000_header.png");
  headerNarrativa[1] = requestImage("narrativa/C_Julia/C000_header.png");
  headerNarrativa[2] = requestImage("narrativa/D_Camila/D000_header.png");
  headerNarrativa[3] = requestImage("narrativa/E_Bernardo/E000_header.png");
  headerNarrativa[4] = requestImage("narrativa/F_Samira/F000_header.png");

  //img = requestImage("narrativa/B_João/G002_maoEsquerda.png");
  //grade? narrativa/G_geral/G003_grade.png

  //narrativa B João
  narrativaB[0] = requestImage("narrativa/B_João/B000.png");
  narrativaB[1] = requestImage("narrativa/B_João/B001.png");
  narrativaB[2] = requestImage("narrativa/B_João/B002.png");
  narrativaB[3] = requestImage("narrativa/B_João/B003.png");
  narrativaB[4] = requestImage("narrativa/B_João/B004.png");
  narrativaB[5] = requestImage("narrativa/B_João/B005.png");
  narrativaB[6] = requestImage("narrativa/B_João/B006.png");
  narrativaB[7] = requestImage("narrativa/B_João/B007.png");
  narrativaB[8] = requestImage("narrativa/B_João/B008.png");
  narrativaB[9] = requestImage("narrativa/B_João/B009.png");
  narrativaB[10] = requestImage("narrativa/B_João/B010.png");
  narrativaB[11] = requestImage("narrativa/B_João/B011.png");
  narrativaB[12] = requestImage("narrativa/B_João/B012.png");
  narrativaB[13] = requestImage("narrativa/B_João/B013.png");
  narrativaB[14] = requestImage("narrativa/B_João/B014.png");
  narrativaB[15] = requestImage("narrativa/B_João/B015.png");
  narrativaB[16] = requestImage("narrativa/B_João/B016.png");
  narrativaB[17] = requestImage("narrativa/B_João/B017.png");
  narrativaB[18] = requestImage("narrativa/B_João/B018.png");
  narrativaB[19] = requestImage("narrativa/B_João/B019.png");
  narrativaB[20] = requestImage("narrativa/B_João/B020.png");
  narrativaB[21] = requestImage("narrativa/B_João/B021.png");
  narrativaB[22] = requestImage("narrativa/B_João/B022.png");
  narrativaB[23] = requestImage("narrativa/B_João/B023.png");
  narrativaB[24] = requestImage("narrativa/B_João/B024.png");
  narrativaB[25] = requestImage("narrativa/B_João/B025.png");
  narrativaB[26] = requestImage("narrativa/B_João/B026.png");
  narrativaB[27] = requestImage("narrativa/B_João/B027.png");
  narrativaB[28] = requestImage("narrativa/B_João/B028.png");
  narrativaB[29] = requestImage("narrativa/B_João/B029.png");
  narrativaB[30] = requestImage("narrativa/B_João/B030.png");
  narrativaB[31] = requestImage("narrativa/B_João/B031.png");
  narrativaB[32] = requestImage("narrativa/B_João/B032.png");
  narrativaB[33] = requestImage("narrativa/B_João/B033.png");
  narrativaB[34] = requestImage("narrativa/B_João/B034.png");
  narrativaB[35] = requestImage("narrativa/B_João/B035.png"); 
  narrativaB[36] = requestImage("narrativa/B_João/B036.png");
  narrativaB[37] = requestImage("narrativa/B_João/B037.png"); 
  narrativaB[38] = requestImage("narrativa/B_João/B038.png");
  narrativaB[39] = requestImage("narrativa/B_João/B039.png"); 
  narrativaB[40] = requestImage("narrativa/B_João/B040.png");
  narrativaB[41] = requestImage("narrativa/B_João/B041.png");
  narrativaB[42] = requestImage("narrativa/B_João/B042.png");
  narrativaB[43] = requestImage("narrativa/B_João/B043.png");
  narrativaB[44] = requestImage("narrativa/B_João/B044.png");
  narrativaB[45] = requestImage("narrativa/B_João/B045.png"); 
  narrativaB[46] = requestImage("narrativa/B_João/B046.png");
  narrativaB[47] = requestImage("narrativa/B_João/B047.png"); 
  narrativaB[48] = requestImage("narrativa/B_João/B048.png");
  narrativaB[49] = requestImage("narrativa/B_João/B049.png"); 
  narrativaB[50] = requestImage("narrativa/B_João/B050.png");
  narrativaB[51] = requestImage("narrativa/B_João/B051.png");
  narrativaB[52] = requestImage("narrativa/B_João/B052.png");
  narrativaB[53] = requestImage("narrativa/B_João/B053.png");
  narrativaB[54] = requestImage("narrativa/B_João/B054.png");
  narrativaB[55] = requestImage("narrativa/B_João/B055.png"); 
  narrativaB[56] = requestImage("narrativa/B_João/B056.png");
  narrativaB[57] = requestImage("narrativa/B_João/B057.png"); 
  narrativaB[58] = requestImage("narrativa/B_João/B058.png");
  narrativaB[59] = requestImage("narrativa/B_João/B059.png"); 
  narrativaB[60] = requestImage("narrativa/B_João/B060.png");

  //narrativa C Julia
  //narrativaCCapa = requestImage("narrativa/C_Julia/C000_header.png");
  narrativaC[0] = requestImage("narrativa/C_Julia/C000.png");
  narrativaC[1] = requestImage("narrativa/C_Julia/C001.png");
  narrativaC[2] = requestImage("narrativa/C_Julia/C002.png");
  narrativaC[3] = requestImage("narrativa/C_Julia/C003.png");
  narrativaC[4] = requestImage("narrativa/C_Julia/C004.png");
  narrativaC[5] = requestImage("narrativa/C_Julia/C005.png");
  narrativaC[6] = requestImage("narrativa/C_Julia/C006.png");
  narrativaC[7] = requestImage("narrativa/C_Julia/C007.png");
  narrativaC[8] = requestImage("narrativa/C_Julia/C008.png");
  narrativaC[9] = requestImage("narrativa/C_Julia/C009.png");
  narrativaC[10] = requestImage("narrativa/C_Julia/C010.png");
  narrativaC[11] = requestImage("narrativa/C_Julia/C011.png");
  narrativaC[12] = requestImage("narrativa/C_Julia/C012.png");
  narrativaC[13] = requestImage("narrativa/C_Julia/C013.png");
  narrativaC[14] = requestImage("narrativa/C_Julia/C014.png");
  narrativaC[15] = requestImage("narrativa/C_Julia/C015.png");
  narrativaC[16] = requestImage("narrativa/C_Julia/C016.png");
  narrativaC[17] = requestImage("narrativa/C_Julia/C017.png");
  narrativaC[18] = requestImage("narrativa/C_Julia/C018.png");
  narrativaC[19] = requestImage("narrativa/C_Julia/C019.png");
  narrativaC[20] = requestImage("narrativa/C_Julia/C020.png");
  narrativaC[21] = requestImage("narrativa/C_Julia/C021.png");
  narrativaC[22] = requestImage("narrativa/C_Julia/C022.png");
  narrativaC[23] = requestImage("narrativa/C_Julia/C023.png");
  narrativaC[24] = requestImage("narrativa/C_Julia/C024.png");
  narrativaC[25] = requestImage("narrativa/C_Julia/C025.png");
  narrativaC[26] = requestImage("narrativa/C_Julia/C026.png");
  narrativaC[27] = requestImage("narrativa/C_Julia/C027.png");
  narrativaC[28] = requestImage("narrativa/C_Julia/C028.png");
  narrativaC[29] = requestImage("narrativa/C_Julia/C029.png");
  narrativaC[30] = requestImage("narrativa/C_Julia/C030.png");
  narrativaC[31] = requestImage("narrativa/C_Julia/C031.png");
  narrativaC[32] = requestImage("narrativa/C_Julia/C032.png");
  narrativaC[33] = requestImage("narrativa/C_Julia/C033.png");
  narrativaC[34] = requestImage("narrativa/C_Julia/C034.png");
  narrativaC[35] = requestImage("narrativa/C_Julia/C035.png");

  //narrativaD Camila 
  //narrativaDCapa = requestImage("narrativa/D_Camila/D000_header.png");
  narrativaD[0] = requestImage("narrativa/D_Camila/D000.png");
  narrativaD[1] = requestImage("narrativa/D_Camila/D001.png");
  narrativaD[2] = requestImage("narrativa/D_Camila/D002.png");
  narrativaD[3] = requestImage("narrativa/D_Camila/D003.png");
  narrativaD[4] = requestImage("narrativa/D_Camila/D004.png");
  narrativaD[5] = requestImage("narrativa/D_Camila/D005.png");
  narrativaD[6] = requestImage("narrativa/D_Camila/D006.png");
  narrativaD[7] = requestImage("narrativa/D_Camila/D007.png");
  narrativaD[8] = requestImage("narrativa/D_Camila/D008.png");
  narrativaD[9] = requestImage("narrativa/D_Camila/D009.png");
  narrativaD[10] = requestImage("narrativa/D_Camila/D010.png");
  narrativaD[11] = requestImage("narrativa/D_Camila/D011.png");
  narrativaD[12] = requestImage("narrativa/D_Camila/D012.png");
  narrativaD[13] = requestImage("narrativa/D_Camila/D013.png");
  narrativaD[14] = requestImage("narrativa/D_Camila/D014.png");
  narrativaD[15] = requestImage("narrativa/D_Camila/D015.png");
  narrativaD[16] = requestImage("narrativa/D_Camila/D016.png");
  narrativaD[17] = requestImage("narrativa/D_Camila/D017.png");
  narrativaD[18] = requestImage("narrativa/D_Camila/D018.png");
  narrativaD[19] = requestImage("narrativa/D_Camila/D019.png");
  narrativaD[20] = requestImage("narrativa/D_Camila/D020.png");
  narrativaD[21] = requestImage("narrativa/D_Camila/D021.png");
  narrativaD[22] = requestImage("narrativa/D_Camila/D022.png");
  narrativaD[23] = requestImage("narrativa/D_Camila/D023.png");
  narrativaD[24] = requestImage("narrativa/D_Camila/D024.png");
  narrativaD[25] = requestImage("narrativa/D_Camila/D025.png");
  narrativaD[26] = requestImage("narrativa/D_Camila/D026.png");
  narrativaD[27] = requestImage("narrativa/D_Camila/D027.png");
  narrativaD[28] = requestImage("narrativa/D_Camila/D028.png");
  narrativaD[29] = requestImage("narrativa/D_Camila/D029.png");
  narrativaD[30] = requestImage("narrativa/D_Camila/D030.png");
  narrativaD[31] = requestImage("narrativa/D_Camila/D031.png");
  narrativaD[32] = requestImage("narrativa/D_Camila/D032.png");


  //narrativaE Bernardo
  //narrativaECapa = requestImage("narrativa/E_Bernardo/E000_header.png");
  narrativaE[0] = requestImage("narrativa/E_Bernardo/E000.png");
  narrativaE[1] = requestImage("narrativa/E_Bernardo/E001.png");
  narrativaE[2] = requestImage("narrativa/E_Bernardo/E002.png");
  narrativaE[3] = requestImage("narrativa/E_Bernardo/E003.png");
  narrativaE[4] = requestImage("narrativa/E_Bernardo/E004.png");
  narrativaE[5] = requestImage("narrativa/E_Bernardo/E005.png");
  narrativaE[6] = requestImage("narrativa/E_Bernardo/E006.png");
  narrativaE[7] = requestImage("narrativa/E_Bernardo/E007.png");
  narrativaE[8] = requestImage("narrativa/E_Bernardo/E008.png");
  narrativaE[9] = requestImage("narrativa/E_Bernardo/E009.png");
  narrativaE[10] = requestImage("narrativa/E_Bernardo/E010.png");
  narrativaE[11] = requestImage("narrativa/E_Bernardo/E011.png");
  narrativaE[12] = requestImage("narrativa/E_Bernardo/E012.png");
  narrativaE[13] = requestImage("narrativa/E_Bernardo/E013.png");
  narrativaE[14] = requestImage("narrativa/E_Bernardo/E014.png");
  narrativaE[15] = requestImage("narrativa/E_Bernardo/E015.png");
  narrativaE[16] = requestImage("narrativa/E_Bernardo/E016.png");
  narrativaE[17] = requestImage("narrativa/E_Bernardo/E017.png");
  narrativaE[18] = requestImage("narrativa/E_Bernardo/E018.png");
  narrativaE[19] = requestImage("narrativa/E_Bernardo/E019.png");
  narrativaE[20] = requestImage("narrativa/E_Bernardo/E020.png");
  narrativaE[21] = requestImage("narrativa/E_Bernardo/E021.png");
  narrativaE[22] = requestImage("narrativa/E_Bernardo/E022.png");
  narrativaE[23] = requestImage("narrativa/E_Bernardo/E023.png");
  narrativaE[24] = requestImage("narrativa/E_Bernardo/E024.png");
  narrativaE[25] = requestImage("narrativa/E_Bernardo/E025.png");
  narrativaE[26] = requestImage("narrativa/E_Bernardo/E026.png");
  narrativaE[27] = requestImage("narrativa/E_Bernardo/E027.png");
  narrativaE[28] = requestImage("narrativa/E_Bernardo/E028.png");
  narrativaE[29] = requestImage("narrativa/E_Bernardo/E029.png");
  narrativaE[30] = requestImage("narrativa/E_Bernardo/E030.png");
  narrativaE[31] = requestImage("narrativa/E_Bernardo/E031.png");
  narrativaE[32] = requestImage("narrativa/E_Bernardo/E032.png");
  narrativaE[33] = requestImage("narrativa/E_Bernardo/E033.png");
  narrativaE[34] = requestImage("narrativa/E_Bernardo/E034.png");
  narrativaE[35] = requestImage("narrativa/E_Bernardo/E035.png"); 
  narrativaE[36] = requestImage("narrativa/E_Bernardo/E036.png");
  narrativaE[37] = requestImage("narrativa/E_Bernardo/E037.png"); 
  narrativaE[38] = requestImage("narrativa/E_Bernardo/E038.png");
  narrativaE[39] = requestImage("narrativa/E_Bernardo/E039.png"); 
  narrativaE[40] = requestImage("narrativa/E_Bernardo/E040.png");
  narrativaE[41] = requestImage("narrativa/E_Bernardo/E041.png");
  narrativaE[42] = requestImage("narrativa/E_Bernardo/E042.png");
  narrativaE[43] = requestImage("narrativa/E_Bernardo/E043.png");
  narrativaE[44] = requestImage("narrativa/E_Bernardo/E044.png");
  narrativaE[45] = requestImage("narrativa/E_Bernardo/E045.png"); 
  narrativaE[46] = requestImage("narrativa/E_Bernardo/E046.png");
  narrativaE[47] = requestImage("narrativa/E_Bernardo/E047.png"); 
  narrativaE[48] = requestImage("narrativa/E_Bernardo/E048.png");
  narrativaE[49] = requestImage("narrativa/E_Bernardo/E049.png"); 
  narrativaE[50] = requestImage("narrativa/E_Bernardo/E050.png");
  narrativaE[51] = requestImage("narrativa/E_Bernardo/E051.png");

  //narrativaF Samira
  //narrativaFCapa = requestImage("narrativa/F_Samira/F000_header.png");
  narrativaF[0] = requestImage("narrativa/F_Samira/F000.png");
  narrativaF[1] = requestImage("narrativa/F_Samira/F001.png");
  narrativaF[2] = requestImage("narrativa/F_Samira/F002.png");
  narrativaF[3] = requestImage("narrativa/F_Samira/F003.png");
  narrativaF[4] = requestImage("narrativa/F_Samira/F004.png");
  narrativaF[5] = requestImage("narrativa/F_Samira/F005.png");
  narrativaF[6] = requestImage("narrativa/F_Samira/F006.png");
  narrativaF[7] = requestImage("narrativa/F_Samira/F007.png");
  narrativaF[8] = requestImage("narrativa/F_Samira/F008.png");
  narrativaF[9] = requestImage("narrativa/F_Samira/F009.png");
  narrativaF[10] = requestImage("narrativa/F_Samira/F010.png");
  narrativaF[11] = requestImage("narrativa/F_Samira/F011.png");
  narrativaF[12] = requestImage("narrativa/F_Samira/F012.png");
  narrativaF[13] = requestImage("narrativa/F_Samira/F013.png");
  narrativaF[14] = requestImage("narrativa/F_Samira/F014.png");
  narrativaF[15] = requestImage("narrativa/F_Samira/F015.png");
  narrativaF[16] = requestImage("narrativa/F_Samira/F016.png");
  narrativaF[17] = requestImage("narrativa/F_Samira/F017.png");
  narrativaF[18] = requestImage("narrativa/F_Samira/F018.png");
  narrativaF[19] = requestImage("narrativa/F_Samira/F019.png");
  narrativaF[20] = requestImage("narrativa/F_Samira/F020.png");
  narrativaF[21] = requestImage("narrativa/F_Samira/F021.png");
  narrativaF[22] = requestImage("narrativa/F_Samira/F022.png");
  narrativaF[23] = requestImage("narrativa/F_Samira/F023.png");
  narrativaF[24] = requestImage("narrativa/F_Samira/F024.png");
  narrativaF[25] = requestImage("narrativa/F_Samira/F025.png");
  narrativaF[26] = requestImage("narrativa/F_Samira/F026.png");
  narrativaF[27] = requestImage("narrativa/F_Samira/F027.png");
  narrativaF[28] = requestImage("narrativa/F_Samira/F028.png");
  narrativaF[29] = requestImage("narrativa/F_Samira/F029.png");
  narrativaF[30] = requestImage("narrativa/F_Samira/F030.png");
  narrativaF[31] = requestImage("narrativa/F_Samira/F031.png");
  narrativaF[32] = requestImage("narrativa/F_Samira/F032.png");
  narrativaF[33] = requestImage("narrativa/F_Samira/F033.png");
  narrativaF[34] = requestImage("narrativa/F_Samira/F034.png");
}
